### ISSUE TITLE
Wrong config

### ISSUE THREAD

**Issue by espensgr** [carlcs/craft-maintenance#1]
I just installed the plugin an it says it takes the config from the file in my config directory, but that file does not exist.

**Comment by carlcs** [comment]
Yes, sorry. It's currently only static text that's always displayed. It is there to make people aware of the possibility to set configuration with a custom craft/config/maintenance.php file.

Proper settings (which can be overridden with a maintenance.php) is coming soon.

**Comment by carlcs** [comment]
@espensgr the latest release now got a proper settings page.

**Comment by espensgr** [comment]
:thumbsup:
