### ISSUE TITLE
Console commands error

### ISSUE THREAD

**Issue by lboaretto** [carlcs/craft-maintenance#4]
Hello,
My console command breaks because your plugin has a REMOTE_ADDR check.

`$ php craft/app/etc/console/yiic migration_site execute 
PHP Error[8]: Undefined index: REMOTE_ADDR
    in file /home/forge/site/craft/app/services/HttpRequestService.php at line 1105
#0 /home/forge/site/craft/app/etc/console/ConsoleApp.php(265): Craft\ConsoleApp->handleError()
#1 /home/forge/site/craft/app/services/HttpRequestService.php(1105): Craft\ConsoleApp->handleError()
#2 /home/forge/site/craft/plugins/maintenance/MaintenancePlugin.php(173): Craft\HttpRequestService->getIpAddress()
#3 /home/forge/site/craft/plugins/maintenance/MaintenancePlugin.php(75): Craft\MaintenancePlugin->initSiteAccessControl()
#4 /home/forge/site/craft/app/services/PluginsService.php(150): Craft\MaintenancePlugin->init()
#5 /home/forge/site/craft/app/etc/console/ConsoleApp.php(86): Craft\PluginsService->loadPlugins()
#6 /home/forge/site/craft/app/framework/base/CApplication.php(170): Craft\ConsoleApp->init()
#7 /home/forge/site/craft/app/framework/YiiBase.php(121): Craft\ConsoleApp->__construct()
#8 /home/forge/site/craft/app/etc/console/yiic.php(87): createApplication()`

To solv, simple edit the line:
https://github.com/carlcs/craft-maintenance/blob/7c13bd5b881f98cc75c25aa48606b07480f0aeb9/MaintenancePlugin.php#L172

to:
`if (!craft()->isConsole() && craft()->request->isSiteRequest() && (!craft()->userSession->checkPermission('maintenanceSiteAccess'))) {`

Thanks!

**Comment by carlcs** [comment]
Thanks, should be fixed in the latest release.

**Comment by lboaretto** [comment]
Thanks!
